### PR TITLE
Update dev-environment.yml

### PR DESCRIPTION
**Pull request by shafferm**
Hey Gavin,

This is the dev-environment.yml change I'd suggested a while ago. Makes it use conda for all dependencies and includes compliers for placement dependencies. Does make it linux specific as a result of the compliers but I think that is all that is explicitly supported currently anyway.

Mike

### CODE REVIEW

**Comment by gavinmdouglas** [comment]
Hi Mike,

Thanks a lot for contributing!

I ran into some errors when trying to install PaPaRa and EPA-NG after installing a new environment based on your updated YAML. I'm thinking that the tools are looking for the system-wide installations of the dependencies and aren't finding them in the conda lib directory. Did you install the placement tools using different commands than what I have [listed](https://github.com/picrust/picrust2/wiki/Pre-requisite-installations)? Or alternatively could you have configured conda in a different way?

This is the head of the error I got when installing PaPaRa:

```
papara.cpp:22:26: fatal error: boost/bind.hpp: No such file or directory
 #include <boost/bind.hpp>
                          ^
compilation terminated.
In file included from pvec.cpp:21:0:
./pvec.h:24:42: fatal error: boost/numeric/ublas/matrix.hpp: No such file or directory
 #include <boost/numeric/ublas/matrix.hpp>
                                          ^
compilation terminated.
```


And when installing EPA-NG:

```
-- Could NOT find BISON (missing:  BISON_EXECUTABLE)
-- Could NOT find FLEX (missing:  FLEX_EXECUTABLE)
CMake Error at libs/pll-modules/libs/libpll/src/CMakeLists.txt:15 (BISON_TARGET):
  Unknown CMake command "BISON_TARGET".
```

Thanks!

**Comment by shafferm** [comment]
I think the server I use has some things preinstalled that I didn't realize. I've added bison flex and boost so that they are installed with the dev-environment.yml. Hopefully that will fix those issues. If we just want to fully round out all the requirements listed with the EPA-NG installation autotools and cmake are also both available in the base anaconda channel. Bonus will be that all compilation could happen within the conda environment and no longer require the user to sudo install anything.

**Comment by gavinmdouglas** [comment]
Thanks again for helping out with this!

I see automake and autoconf on the base channel, but not autotools actually - is that what you meant?

Installing bison and flex with conda allow EPA-NG to be installed correctly!

But unfortunately I'm still getting a boost error when trying to install PaPaRa:
```
papara.cpp:22:26: fatal error: boost/bind.hpp: No such file or directory
 #include <boost/bind.hpp>
                          ^
compilation terminated.
In file included from pvec.cpp:21:0:
./pvec.h:24:42: fatal error: boost/numeric/ublas/matrix.hpp: No such file or directory
 #include <boost/numeric/ublas/matrix.hpp>
                                          ^
compilation terminated.
```

Installing Libboost with conda as well didn't fix this.

**Comment by gavinmdouglas** [comment]
Hi @shafferm, just to let you know that I haven't forgotten about this! I've been battling with making a conda package for EPA-NG and I think I'm close to getting it working.

**Comment by shafferm** [comment]
@gavinmdouglas Not a problem. I haven't had time to dive into it again either. I have a package in bioconda so let me know if you need any help with that recipe.

**Comment by gavinmdouglas** [comment]
I added EPA-NG and GAPPA to bioconda so this will be resolved in the next major update.

**Pull request closed without merging**
